/**
 * Session export utilities — CSV and print-friendly HTML
 * @module utils/exportSessions
 */

/**
 * Convert sessions array to CSV string.
 * @param {object[]} sessions
 * @param {number} hz - Display refresh rate
 * @returns {string}
 */
export function sessionsToCSV(sessions, hz) {
  const headers = ['Date', 'Time', 'Exercise', 'Threshold (ms)', 'Accuracy (%)', 'Duration (min)', 'Trials'];
  const rows = sessions.map((s) => {
    const date = s.completedAt ? new Date(s.completedAt) : null;
    const dateStr = date ? date.toLocaleDateString() : '';
    const timeStr = date ? date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' }) : '';
    const exLabel = s.exerciseType === 1 ? 'Ex 1: Central Focus'
      : s.exerciseType === 2 ? 'Ex 2: Divided Attention'
      : s.exerciseType === 3 ? 'Ex 3: Selective Attention'
      : `Ex ${s.exerciseType}`;
    const thresholdMs = Math.round(((s.thresholdFrames || 0) / hz) * 1000);
    const accuracy = Math.round((s.accuracy || 0) * 100);
    const duration = s.durationMs ? (Math.round(s.durationMs / 60000 * 10) / 10).toFixed(1) : '';
    const trialCount = s.trials ? s.trials.length : '';

    return [dateStr, timeStr, exLabel, thresholdMs, accuracy, duration, trialCount]
      .map((v) => `"${v}"`)
      .join(',');
  });

  return [headers.join(','), ...rows].join('\n');
}

/**
 * Trigger CSV file download in the browser.
 * @param {string} csvString
 * @param {string} filename
 */
export function downloadCSV(csvString, filename = 'cognify-sessions.csv') {
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Open a print-friendly page with session data (zero-dependency PDF alternative).
 * @param {object[]} sessions
 * @param {number} hz
 */
export function printSessions(sessions, hz) {
  const rows = sessions.map((s) => {
    const date = s.completedAt ? new Date(s.completedAt) : null;
    const dateStr = date ? date.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : '';
    const timeStr = date ? date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' }) : '';
    const exLabel = s.exerciseType === 1 ? 'Central Focus'
      : s.exerciseType === 2 ? 'Divided Attention'
      : s.exerciseType === 3 ? 'Selective Attention'
      : `Exercise ${s.exerciseType}`;
    const thresholdMs = Math.round(((s.thresholdFrames || 0) / hz) * 1000);
    const accuracy = Math.round((s.accuracy || 0) * 100);

    return `<tr>
      <td style="padding:8px 12px;border-bottom:1px solid #e4e0d8">${dateStr}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e4e0d8">${timeStr}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e4e0d8">${exLabel}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e4e0d8;text-align:right;font-weight:bold">${thresholdMs}ms</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e4e0d8;text-align:right">${accuracy}%</td>
    </tr>`;
  }).join('\n');

  const html = `<!DOCTYPE html>
<html><head>
<title>Cognify Session History</title>
<style>
  body { font-family: 'Segoe UI', system-ui, sans-serif; color: #2e3230; margin: 40px; }
  h1 { color: #4a7c59; font-size: 24px; margin-bottom: 4px; }
  .subtitle { color: #6b6358; margin-bottom: 24px; }
  table { border-collapse: collapse; width: 100%; }
  th { text-align: left; padding: 10px 12px; background: #f0ece4; color: #4a7c59; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { font-size: 14px; }
  .footer { margin-top: 32px; color: #74796e; font-size: 12px; }
</style>
</head><body>
<h1>Cognify Session History</h1>
<p class="subtitle">Exported on ${new Date().toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' })}</p>
<table>
  <thead><tr>
    <th>Date</th><th>Time</th><th>Exercise</th><th style="text-align:right">Threshold</th><th style="text-align:right">Accuracy</th>
  </tr></thead>
  <tbody>${rows}</tbody>
</table>
<p class="footer">Generated by Cognify — Share this data with your healthcare provider to track cognitive progress.</p>
</body></html>`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  }
}
